Add full text search sample data and the script
danduk82/package_gmf pull request #2
Opened 2020-05-04 15:33 UTC by ismailsunni

2020-05-05 08:44 UTC, danduk82 requested changes

2020-05-05 08:44 UTC, danduk82 commented on scripts/initialize.sh
> +        ST_TRANSFORM(wkb_geometry, 2056),
please change the CRS to `3857` instead of `2056`, we are using webmercator in this project

2020-05-05 08:44 UTC, danduk82 commented on scripts/initialize.sh
> +    configure_full_text_search
you should first configure the TS (new languages) and then restore the DB, otherwise it **might** not be able to write the records if the `en` and `de` languages are not present (not sure though)

2020-05-07 11:26 UTC, ismailsunni commented on scripts/initialize.sh
> +    configure_full_text_search
Fixed

2020-05-07 11:27 UTC, ismailsunni commented on scripts/initialize.sh
> +    configure_full_text_search
It seems it's working fine

2020-05-08 09:00 UTC, danduk82 requested changes
looks quite good. just a minor change please

2020-05-08 09:00 UTC, danduk82 commented on scripts/initialize.sh
> +    if [[ ! ${tsearchTableTest} -gt 1 ]] ; then
could you please put this check inside the function `create_tsearch_table` so that in the main we just call it, and the decision to create it or not is at the beginning of the function?

2020-05-08 09:00 UTC, danduk82 commented on scripts/initialize.sh
> +    docker exec ${package_name}_db psql -c "SELECT UpdateGeometrySRID('main', 'tsearch', 'the_geom', 3857);"
:+1:

2020-05-08 12:17 UTC, danduk82 approved these changes

2020-05-08 12:17 UTC, danduk82 commented
thanks @ismailsunni

2020-05-08 12:17 UTC, merged